import NextHead from "next/head"

interface Props {
  title?: string
}

export const Head = ({ title }: Props) => (
  <NextHead>
    <title>{title}</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </NextHead>
)
